#pragma once

enum ModelType
{
    WOODEN_SWORD_MODEL,
    ROYAL_SWORD_MODEL,
    MASTER_SWORD_MODEL,
    WOODEN_SWORD_IN_INVENTORY_MODEL,
    ROYAL_SWORD_IN_INVENTORY_MODEL,
    MASTER_SWORD_IN_INVENTORY_MODEL,
    MILK_MODEL,
    HEALTH_POTION_MODEL,
    FAIRY_MODEL,
    KEY_MODEL,
    HEALTH_MODEL,
    MONSTER_01_MODEL,
    MONSTER_02_MODEL,
    MONSTER_03_MODEL,
    LADDER_MODEL,
    CHEST_MODEL,
    MONEY_MODEL,
    DOOR_MODEL,
    INVENTORY_MODEL,
    MENU_MODEL,
    NONE // To return a value in function Player::getModelType()
};